### ISSUE TITLE
Multiple set-cookie headers being ignored in response

### ISSUE THREAD

**Issue by pratikshelar87** [dreamhead/moco#232]
If there are multiple set-cookie headers moco is just sending the last header in the response
`{
    "description": "session request",
    "request": {
      "uri": "/session",
      "method": "post"
    },
    "response": {
      "status": "200",
      "headers": {
        "set-cookie": "testCookie1=test1234; path=/; httpOnly=true",
        "set-cookie": "testCookie2=test1234; path=/; httpOnly=true"
      },
      "file": "valid-session.json"
    }
  }`

The above config results in the set-cookie header having only testCookie2. The test-cookie1 gets missing.

I even tried a different config but with same results

`{
    "description": "session request",
    "request": {
      "uri": "/session",
      "method": "post"
    },
    "response": {
      "status": "200",
      "cookies": {
        "testCookie1": {
          "value":"12345"
        },
        "testCookie2":{
          "value":"Test1234"
        }
       },
      "file": "valid-session.json"
    }
  }`

**Comment by dreamhead** [comment]
The published Moco does not support header with same name that is why your solution does not work.

I've already fixed it in Moco repository which will be included in next Moco release.

**Comment by yanpeng1210** [comment]
> The published Moco does not support header with same name that is why your solution does not work.
> 
> I've already fixed it in Moco repository which will be included in next Moco release.

Why do I still have the same problem?
![image](https://user-images.githubusercontent.com/19601611/53101580-09915800-3565-11e9-9790-eebe7d298410.png)
![image](https://user-images.githubusercontent.com/19601611/53101662-2ded3480-3565-11e9-87b1-54d9a76f3707.png)

**Comment by dreamhead** [comment]
You mean new Moco should be released. :)
